#!/usr/bin/env python3
# Generates Lumi/Localizable.xcstrings (source = zh-Hans; keys = Chinese source strings).
import json, sys

# (zh source key, en, ar)
S = [
 # Tabs
 ("地图","Map","الخريطة"),
 ("星迹","Trails","المسارات"),
 ("成就","Awards","الإنجازات"),
 ("我","Me","أنا"),
 # Map home
 ("已点亮 FOOTPRINTS LIT","FOOTPRINTS LIT","المواقع المضاءة"),
 ("/ %lld 国","/ %lld countries","/ %lld دولة"),
 ("%lld 座城市 · 全球 %@","%lld cities · %@ of the world","%lld مدينة · %@ من العالم"),
 ("世界进度 World","World Progress","تقدّم العالم"),
 ("精彩瞬间","Highlights","أبرز اللحظات"),
 ("点亮新足迹","Light a new spot","أضئ موقعًا جديدًا"),
 # Timeline
 ("Footprints","Footprints","البصمات"),
 ("从相册同步","Sync from Photos","مزامنة من الصور"),
 ("还没有星迹","No trails yet","لا مسارات بعد"),
 ("从相册一键找回去过的地方，或回地图点亮第一个","Recover places from your photos, or light your first on the map","استعد الأماكن من صورك، أو أضئ أول موقع على الخريطة"),
 ("从相册同步历史足迹","Sync past footprints from Photos","مزامنة البصمات السابقة من الصور"),
 ("删除这条足迹？","Delete this footprint?","حذف هذه البصمة؟"),
 ("删除","Delete","حذف"),
 ("取消","Cancel","إلغاء"),
 ("%lld · 已记录 %lld 段","%1$lld · %2$lld recorded","%1$lld · %2$lld مسجّلة"),
 # Footprint detail / edit
 ("同行人","Companions","الرفاق"),
 ("日期","Date","التاريخ"),
 ("照片","Photos","الصور"),
 ("地区","Region","المنطقة"),
 ("国家","Country","الدولة"),
 ("编辑足迹","Edit Footprint","تعديل البصمة"),
 ("保存","Save","حفظ"),
 ("地点名","Place name","اسم المكان"),
 ("一句心情","A note","انطباع"),
 ("多天行程","Multi-day trip","رحلة متعددة الأيام"),
 ("和谁一起？","With whom?","مع مَن؟"),
 ("开始","Start","البداية"),
 ("结束","End","النهاية"),
 ("记一句此刻的感受…","Write how this moment feels…","اكتب شعورك في هذه اللحظة…"),
 # Capture
 ("新足迹","New Footprint","بصمة جديدة"),
 ("加一张照片（可跳过）","Add a photo (optional)","أضف صورة (اختياري)"),
 ("地点","Place","المكان"),
 ("搜索地点","Search a place","ابحث عن مكان"),
 ("点亮这里 ✦","Light up here ✦","أضئ هنا ✦"),
 ("更改","Change","تغيير"),
 # Profile
 ("我的世界","My World","عالمي"),
 ("Lv.%lld 探索者","Lv.%lld Explorer","المستوى %lld مستكشف"),
 ("国家","Countries","الدول"),  # NOTE dup key resolved below
 ("城市","Cities","المدن"),
 ("勋章","Badges","الأوسمة"),
 ("距离 Lv.%lld 还差 %lld 国","%2$lld more countries to Lv.%1$lld","%2$lld دولة للوصول للمستوى %1$lld"),
 ("最近点亮 Recent","Recently Lit","أُضيئت مؤخرًا"),
 ("还没有足迹 · 回地图点亮第一个地方","No footprints yet · light your first on the map","لا بصمات بعد · أضئ أول موقع على الخريطة"),
 ("未知地区","Unknown region","منطقة غير معروفة"),
 ("未知地点","Unknown place","مكان غير معروف"),
 # Settings
 ("设置","Settings","الإعدادات"),
 ("语言 Language","Language","اللغة"),
 ("语言跟随系统","Language follows system","اللغة تتبع النظام"),
 ("在「系统设置 › Lumi」里可单独为本应用选择语言","Choose a per-app language in Settings › Lumi","اختر لغة للتطبيق من الإعدادات › Lumi"),
 # Wishlist
 ("心愿单","Wishlist","قائمة الأمنيات"),
 ("还没有心愿","No wishes yet","لا أمنيات بعد"),
 ("搜索添加想去的地方，或在地图上点选标记","Search to add places you want to visit, or tap them on the map","ابحث لإضافة أماكن تريد زيارتها، أو حدّدها على الخريطة"),
 ("添加心愿","Add a wish","أضف أمنية"),
 ("搜索想去的城市 / 国家","Search a city / country","ابحث عن مدينة / دولة"),
 ("还没去过的热门目的地","Popular spots you haven't been","وجهات شهيرة لم تزرها بعد"),
 ("热门目的地都在你的清单里了 ✦","All popular spots are on your list ✦","كل الوجهات الشهيرة في قائمتك ✦"),
 # Photo import
 ("同步历史足迹","Sync Past Footprints","مزامنة البصمات السابقة"),
 ("关闭","Close","إغلاق"),
 ("全选","Select All","تحديد الكل"),
 ("全不选","Deselect All","إلغاء التحديد"),
 ("请求相册权限…","Requesting photo access…","طلب الوصول إلى الصور…"),
 ("正在从相册识别去过的地方…","Finding places from your photos…","يتم التعرف على الأماكن من صورك…"),
 ("无法访问相册","Can't access Photos","تعذّر الوصول إلى الصور"),
 ("到「设置 › 隐私 › 照片」允许 Lumi 读取相册后再试。","Allow Lumi in Settings › Privacy › Photos, then try again.","اسمح لـ Lumi من الإعدادات › الخصوصية › الصور ثم أعد المحاولة."),
 ("打开设置","Open Settings","فتح الإعدادات"),
 ("没找到带位置的新照片","No new located photos found","لم يُعثر على صور جديدة بموقع"),
 ("相册里带定位信息的照片都已点亮，或暂时没有可识别的地点。","All located photos are already lit, or none could be recognized.","كل الصور ذات الموقع مضاءة مسبقًا، أو تعذّر التعرف على أي مكان."),
 ("识别到 %lld 处地点","%lld places found","تم العثور على %lld مكان"),
 ("导入 %lld 个足迹 ✦","Import %lld footprints ✦","استيراد %lld بصمة ✦"),
 ("选择要导入的地点","Select places to import","اختر أماكن للاستيراد"),
 ("按城市","By city","حسب المدينة"),
 ("按国家","By country","حسب الدولة"),
 # Real map screen
 ("点一个国家：标记去过或加入心愿","Tap a country: mark visited or add to wishlist","انقر دولة: حدّدها كمزارة أو أضفها للأمنيات"),
 ("已点亮 · 再记一次","Lit · log again","مضاءة · سجّل مجددًا"),
 ("我去过这里 ✦","I've been here ✦","لقد زرت هنا ✦"),
 ("加入心愿单","Add to wishlist","أضف للأمنيات"),
 ("你哪一年去的 %@？","Which year did you visit %@?","في أي عام زرت %@؟"),
 ("%lld 年","%lld","%lld"),
 ("%@ 年","%@","%@"),
 ("点亮 ✦","Light up ✦","أضئ ✦"),
 ("这个国家","this country","هذه الدولة"),
 # Rarity
 ("普通","Common","عادي"),
 ("稀有","Rare","نادر"),
 ("史诗","Epic","ملحمي"),
 ("传说","Legendary","أسطوري"),
 # BadgeCategory
 ("探索","Explore","استكشاف"),
 ("大洲","Continents","القارات"),
 ("里程碑","Milestones","محطات"),
 ("连续","Streaks","تتابع"),
 # Region
 ("亚洲","Asia","آسيا"),
 ("欧洲","Europe","أوروبا"),
 ("中东","Middle East","الشرق الأوسط"),
 ("美洲","Americas","الأمريكتان"),
 ("非洲","Africa","إفريقيا"),
 ("大洋洲","Oceania","أوقيانوسيا"),
 # Stats view
 ("徽章收藏","Badge Collection","مجموعة الأوسمة"),
 ("已点亮国","Lit countries","الدول المضاءة"),
 ("全部","All","الكل"),
 ("即将解锁 Next up","Next up","التالي"),
 ("大洲征服 Conquest","Continent Conquest","غزو القارات"),
 ("桂冠 · 最高荣耀","Crown · Top honor","التاج · أعلى شرف"),
 ("取消置顶","Unpin","إلغاء التثبيت"),
 ("置顶","Pin","تثبيت"),
 ("设为置顶展示","Pin as featured","تثبيت كمميّز"),
 ("已解锁","Unlocked","مفتوح"),
 ("解锁条件","How to unlock","كيفية الفتح"),
 ("◆ 全球仅 %@ 玩家拥有","◆ Only %@ of players own this","◆ %@ فقط من اللاعبين يملكونه"),
 ("全球持有率","Global ownership","نسبة الامتلاك"),
 ("获得时间","Earned on","تاريخ الحصول"),
 ("当前进度","Progress","التقدم"),
 ("状态","Status","الحالة"),
 ("已获得","Earned","تم الحصول"),
 ("进行中","In progress","قيد التقدم"),
 ("未解锁","Locked","مقفل"),
 ("成就解锁 · UNLOCKED","ACHIEVEMENT · UNLOCKED","إنجاز · مفتوح"),
 ("即将解锁 · %@","Almost there · %@","اقتربت · %@"),
 ("点击任意处继续","Tap anywhere to continue","انقر في أي مكان للمتابعة"),
 # progress units
 ("国","countries","دولة"),
 ("城","cities","مدينة"),
 ("洲","continents","قارة"),
 # Badge names（与徽章图上印字逐一对齐：中/英/阿）
 ("初见曙光","First Light","أول ضوء"),
 ("五国足迹","Five Countries","خمس دول"),
 ("环球旅人","Globetrotter","جوّال العالم"),
 ("沙漠先锋","Desert Pioneer","رائد الصحراء"),
 ("百城达人","Hundred Cities","مئة مدينة"),
 ("七大洲全集","All Continents","كل القارات"),
 ("亚洲之星","Star of Asia","نجم آسيا"),
 ("欧洲漫游者","Europe Roamer","جوّال أوروبا"),
 ("非洲先锋","Africa Pioneer","رائد أفريقيا"),
 ("美洲征服者","Americas Conqueror","فاتح الأمريكتين"),
 ("大洋洲游牧者","Oceania Nomad","بدوي أوقيانوسيا"),
 ("南极探险家","Antarctica Explorer","مستكشف القطب الجنوبي"),
 ("南极先锋","Antarctica Pioneer","رائد القطب الجنوبي"),
 ("丛林探险家","Jungle Explorer","مستكشف الأدغال"),
 ("跳岛旅人","Island Hopper","متنقّل الجزر"),
 # Badge descriptions
 ("点亮你的第一个足迹。旅程由此开始。","Light your first footprint. The journey begins.","أضئ بصمتك الأولى. تبدأ الرحلة هنا."),
 ("全球累计点亮 5 个不同国家。","Light up 5 different countries.","أضئ 5 دول مختلفة."),
 ("点亮 30 个国家解锁这枚史诗徽章。","Light up 30 countries to unlock this epic badge.","أضئ 30 دولة لفتح هذا الوسام الملحمي."),
 ("在干旱 / 沙漠气候城市（如阿布扎比、迪拜）打卡。","Check in at an arid / desert city (e.g. Abu Dhabi, Dubai).","سجّل وصولًا في مدينة صحراوية (مثل أبوظبي، دبي)."),
 ("全球累计打卡的不同城市总数达 100。","Reach 100 distinct cities checked in worldwide.","بلوغ 100 مدينة مختلفة حول العالم."),
 ("全球 7 个大洲均至少含 1 个点亮足迹。","Light at least one footprint on all 7 continents.","أضئ بصمة واحدة على الأقل في كل القارات السبع."),
 ("在亚洲点亮足迹。","Light a footprint in Asia.","أضئ بصمة في آسيا."),
 ("在欧洲点亮足迹。","Light a footprint in Europe.","أضئ بصمة في أوروبا."),
 ("在非洲点亮首个国家。","Light your first country in Africa.","أضئ أول دولة في إفريقيا."),
 ("在北美 / 南美点亮首个国家。","Light your first country in the Americas.","أضئ أول دولة في الأمريكتين."),
 ("在大洋洲点亮首个国家。","Light your first country in Oceania.","أضئ أول دولة في أوقيانوسيا."),
 ("在南极洲（南纬 60° 以下）成功打卡。","Check in within Antarctica (below 60°S).","سجّل وصولًا في القطب الجنوبي (تحت 60° جنوبًا)."),
 ("多次造访南极极寒点（≥ 2 次）。","Visit Antarctica's frozen points more than once (≥ 2).","زر نقاط القطب الجنوبي المتجمدة أكثر من مرة (≥ 2)."),
 ("在雨林覆盖率极高国家（如巴西、印尼）打卡。","Check in at a rainforest-rich country (e.g. Brazil, Indonesia).","سجّل وصولًا في دولة غنية بالغابات المطيرة (مثل البرازيل، إندونيسيا)."),
 ("点亮 3 个不相连的岛屿国家 / 地区。","Light 3 separate island nations / regions.","أضئ 3 دول / مناطق جزرية منفصلة."),
 # —— 本轮新增 UI 文案 ——
 ("增加","Add","إضافة"),
 ("最多 %lld 张 · 已选 %lld","Up to %1$lld · %2$lld selected","حتى %1$lld · %2$lld محدد"),
 ("不展示徽章","Don't feature any","عدم عرض أي وسام"),
 ("小组件 Widgets","Widgets","الودجات"),
 ("点亮计数","Lit Count","عدّاد الإضاءة"),
 ("主屏 / 锁屏显示已点亮国家数与全球占比","Lit countries & world % on home/lock screen","الدول المضاءة ونسبة العالم على الشاشة الرئيسية/المقفلة"),
 ("去年今日","On This Day","في مثل هذا اليوم"),
 ("回看往年此刻去过的地方","Revisit where you were in past years","تذكّر أين كنت في السنوات الماضية"),
 ("添加方式：长按桌面空白处 → 左上角「+」→ 搜索 “Lumi” → 选择小组件。小组件文案跟随系统语言。","To add: long-press the home screen → “+” top-left → search “Lumi” → pick a widget. Widget text follows the system language.","للإضافة: اضغط مطولًا على الشاشة الرئيسية ← «+» أعلى اليسار ← ابحث «Lumi» ← اختر ودجت. نص الودجت يتبع لغة النظام."),
 ("城市（可选）","City (optional)","المدينة (اختياري)"),
 ("打卡城市（可选 · 可多选）","Cities (optional · multi-select)","المدن (اختياري · متعدد)"),
 ("点亮 %lld 城 ✦","Light %lld cities ✦","أضئ %lld مدينة ✦"),
 ("明信片","Postcard","بطاقة بريدية"),
 ("明信片寄语","Postcard note","عبارة البطاقة"),
 ("在明信片上写点什么…","Write something on the postcard…","اكتب شيئًا على البطاقة…"),
 ("分享明信片","Share postcard","مشاركة البطاقة"),
 ("想把%@的这一刻寄给你 ✦","Wish you were here in %@ ✦","ليتك كنت هنا في %@ ✦"),
 ("复制口令","Copy code","نسخ الرمز"),
 ("已复制口令","Code copied","تم نسخ الرمز"),
 ("二维码","QR code","رمز QR"),
 ("或发口令 / 二维码 —— 对方在 Lumi 里自动收下","Or send a code / QR — they receive it inside Lumi","أو أرسل رمزًا / QR — يستلمونه داخل Lumi"),
 ("收到一张明信片 ✦","You received a postcard ✦","وصلتك بطاقة بريدية ✦"),
 ("收下 ✦","Accept ✦","استلام ✦"),
 ("忽略","Ignore","تجاهل"),
 ("%@ 寄来 · %@","From %1$@ · %2$@","من %1$@ · %2$@"),
 ("复制链接","Copy link","نسخ الرابط"),
 ("已复制","Copied","تم النسخ"),
 ("隔空投送","AirDrop","AirDrop"),
 ("链接 / 二维码 / 隔空投送 —— 对方扫码或点开即在 Lumi 收下","Link / QR / AirDrop — they scan or tap to receive in Lumi","رابط / QR / AirDrop — يمسحون أو ينقرون للاستلام في Lumi"),
 ("扫码收明信片","Scan to receive","امسح للاستلام"),
 ("把二维码放进取景框","Place the QR code in the frame","ضع رمز QR داخل الإطار"),
 ("把二维码放进取景框，或从相册选二维码","Place the QR in the frame, or pick one from Photos","ضع رمز QR في الإطار أو اختر صورة من المعرض"),
 ("从相册选二维码","Pick QR from Photos","اختر QR من الصور"),
 ("相机不可用时，也可从相册选一张含二维码的图收下明信片。","No camera? Pick a photo containing a QR to receive the postcard.","بلا كاميرا؟ اختر صورة تحتوي على QR لاستلام البطاقة."),
 ("相册","Photos","الصور"),
 ("没在这张图里找到二维码","No QR code found in this image","لم يُعثر على رمز QR في هذه الصورة"),
 ("此设备无法扫码","This device can't scan","لا يمكن المسح على هذا الجهاز"),
 ("可改用「复制口令 / 隔空投送」接收。","Use Copy link / AirDrop instead.","استخدم نسخ الرابط / AirDrop بدلًا من ذلك."),
 ("明信片墙","Postcards","البطاقات"),
 ("还没有明信片","No postcards yet","لا بطاقات بعد"),
 ("点亮足迹会生成明信片；收到的明信片也会收进这里","Lighting footprints creates postcards; received ones land here too","إضاءة البصمات تنشئ بطاقات؛ والمستلمة تظهر هنا أيضًا"),
 ("我的","Mine","لي"),
 ("收到的","Received","المستلمة"),
 ("✦ 收到","✦ Received","✦ مستلمة"),
 ("护照本","Passport","جواز السفر"),
 ("我的护照本","My passport","جواز سفري"),
 ("去过 %lld 国 · 翻开看看出入境章","%lld countries · open to see your stamps","%lld دولة · افتح لرؤية الأختام"),
 ("去过 %lld 国 · %lld 城","%1$lld countries · %2$lld cities","%1$lld دولة · %2$lld مدينة"),
 ("护照还是空的","Passport is empty","جواز السفر فارغ"),
 ("去点亮第一个国家，盖下第一枚入境章","Light your first country to earn your first stamp","أضئ أول دولة لتحصل على أول ختم"),
 ("个人资料","Profile","الملف الشخصي"),
 ("昵称","Name","الاسم"),
 ("你的昵称","Your name","اسمك"),
 ("国籍","Nationality","الجنسية"),
 ("选择国籍","Choose nationality","اختر الجنسية"),
 ("完成","Done","تم"),
 ("还没有收到明信片","No postcards received yet","لم تصلك بطاقات بعد"),
 ("朋友用扫码 / 链接 / 隔空投送寄来的明信片，会收进这里","Postcards friends send via QR / link / AirDrop land here","البطاقات التي يرسلها الأصدقاء عبر QR / رابط / AirDrop تظهر هنا"),
 ("收到的明信片都在这","Postcards you've received","البطاقات التي استلمتها"),
 ("想去的地方","Places you want to go","أماكن تريد زيارتها"),
 ("今年的足迹","This year","هذا العام"),
 ("分享徽章","Share badge","مشاركة الوسام"),
 ("分享","Share","مشاركة"),
 ("去过的国旗","Flags visited","أعلام زرتها"),
 ("展示去过国家的国旗集合（最多 5 个）","Flags of countries you've visited (up to 5)","أعلام الدول التي زرتها (حتى 5)"),
 ("✦ 成就解锁 · Lit on Lumi","✦ Achievement · Lit on Lumi","✦ إنجاز · على Lumi"),
 # —— B4 变现 / Lumi Plus ——
 ("Lumi Plus","Lumi Plus","Lumi Plus"),
 ("按月","Monthly","شهري"),
 ("按年","Yearly","سنوي"),
 ("终身","Lifetime","مدى الحياة"),
 ("恢复购买","Restore","استعادة المشتريات"),
 ("解锁更精致的明信片与更多记忆增益","Unlock finer postcards and more memory perks","افتح بطاقات أرقى ومزايا ذكريات إضافية"),
 ("明信片无水印 · 高清导出","Postcards: no watermark · HD export","بطاقات بلا علامة مائية · تصدير عالي الدقة"),
 ("去掉 Lumi 水印，3 倍分辨率导出","Remove the Lumi watermark, export at 3× resolution","أزل علامة Lumi المائية وصدّر بدقة 3×"),
 ("全部明信片样式 & 邮票","All postcard styles & stamps","كل أنماط البطاقات والطوابع"),
 ("解锁所有卡面样式与邮票贴图","Unlock every card style and stamp","افتح كل أنماط البطاقات والطوابع"),
 ("地图皮肤 & 主题","Map skins & themes","سمات وأشكال الخريطة"),
 ("更多地图配色与主题","More map palettes and themes","ألوان وسمات خريطة إضافية"),
 ("云同步 · 多设备 · 跨平台","Cloud sync · multi-device · cross-platform","مزامنة سحابية · أجهزة متعددة · متعدد المنصات"),
 ("换机不丢，iOS / Android 共享权益","Never lose data; share Plus across iOS / Android","لا تفقد بياناتك؛ شارك Plus بين iOS و Android"),
 ("进阶统计 · 年度回顾","Advanced stats · year in review","إحصاءات متقدمة · مراجعة سنوية"),
 ("更深的足迹洞察与年度叙事","Deeper footprint insights and yearly stories","رؤى أعمق للبصمات وقصص سنوية"),
 ("现已可用","Available now","متاح الآن"),
 ("即将推出","Coming soon","قريبًا"),
 ("省","Save","وفّر"),
 ("每月 · 随时取消","Monthly · cancel anytime","شهري · ألغِ في أي وقت"),
 ("每年 · 折合更省","Yearly · best value","سنوي · أفضل قيمة"),
 ("一次性买断 · 永久","One-time · forever","دفعة واحدة · للأبد"),
 ("开始订阅","Subscribe","اشترك"),
 ("解锁终身 Plus","Unlock lifetime Plus","افتح Plus مدى الحياة"),
 # —— 终身会员（早鸟一次性买断）——
 ("终身会员","Lifetime member","عضو مدى الحياة"),
 ("早鸟会员","Early bird","عضوية مبكرة"),
 ("成为终身会员","Become a lifetime member","كن عضوًا مدى الحياة"),
 ("一次买断 · 永久解锁 · 含后续功能与常规内容包","One-time · forever · future features & regular content packs","دفعة واحدة · للأبد · الميزات القادمة وحزم المحتوى الاعتيادية"),
 ("后续所有功能迭代与常规内容包","All future features & regular content packs","كل الميزات القادمة وحزم المحتوى الاعتيادية"),
 ("一次解锁，未来新增 Plus 功能与商店常规资源包全部包含（限量/联名款除外，会员享折扣）","Unlock once; every future Plus feature and regular store pack included (limited/collab drops sold separately, members get a discount)","افتح مرة واحدة؛ كل ميزات Plus القادمة وحزم المتجر الاعتيادية مشمولة (الإصدارات المحدودة تُباع منفصلة بخصم للأعضاء)"),
 ("一次性买断，永久解锁全部功能、后续所有功能迭代与商店常规内容包。付款将在确认购买时记入你的 Apple ID，不会自动续费。","A one-time purchase unlocks every feature forever, including all future features and regular store content packs. Payment is charged to your Apple ID at confirmation and does not auto-renew.","عملية شراء لمرة واحدة تفتح كل الميزات للأبد، بما في ذلك الميزات القادمة وحزم المحتوى الاعتيادية. يُخصم المبلغ من Apple ID عند التأكيد ولا يتجدد تلقائيًا."),
 ("终身会员 · 早鸟","Lifetime · Early bird","مدى الحياة · مبكر"),
 # —— 明信片墙统计 ——
 ("收到的明信片","Postcards received","البطاقات المستلمة"),
 ("往来的人","Correspondents","المراسلون"),
 # —— 收集图鉴 ——
 ("收集图鉴","Collection Codex","سِجل المقتنيات"),
 ("邮票 · 邮戳 · 节日章","Stamps · postmarks · festival seals","طوابع · أختام بريد · أختام الأعياد"),
 ("地区邮票","Regional stamps","طوابع المناطق"),
 ("点亮该国家即解锁，可贴在寄出的明信片上","Light up the country to unlock; use it on postcards you send","أضئ الدولة لفتحه؛ استخدمه على بطاقاتك المرسلة"),
 ("节日限定章","Festival seals","أختام الأعياد"),
 ("收到命中节日期间寄出的明信片即可收集","Collect by receiving a postcard sent during the festival window","اجمعه باستلام بطاقة أُرسلت خلال فترة العيد"),
 ("基础邮票 · 邮戳","Basic stamps · postmark","الطوابع الأساسية · ختم البريد"),
 ("默认解锁","Unlocked by default","مفتوح افتراضيًا"),
 ("通用邮戳","Standard postmark","ختم البريد العام"),
 ("已收集 %lld / %lld","Collected %1$lld / %2$lld","تم جمع %1$lld / %2$lld"),
 ("邮票、邮戳与节日章都收进这本图鉴","Every stamp, postmark and festival seal lives in this codex","كل الطوابع وأختام البريد وأختام الأعياد في هذا السِجل"),
 ("点亮 %@ 解锁","Light up %@ to unlock","أضئ %@ للفتح"),
 # —— 节日章名（图鉴展示）——
 ("先知诞辰","Mawlid","المولد النبوي"),
 ("阿联酋国庆","UAE National Day","اليوم الوطني الإماراتي"),
 ("感恩节","Thanksgiving","عيد الشكر"),
 ("圣诞节","Christmas","عيد الميلاد"),
 ("中秋","Mid-Autumn","منتصف الخريف"),
 ("中国国庆","China National Day","العيد الوطني الصيني"),
 ("中东足迹","Middle East footprints","بصمات الشرق الأوسط"),
 ("欧美与亚洲足迹","Western & Asian footprints","بصمات الغرب وآسيا"),
 ("中国足迹","China footprints","بصمات الصين"),
 # —— 地图皮肤 / App 图标（Plus）——
 ("地图皮肤","Map skins","سمات الخريطة"),
 ("换一套点亮配色 · 霓虹免费，更多皮肤属 Plus","Swap the glow palette · Neon is free, more skins with Plus","بدّل ألوان الإضاءة · نيون مجاني والمزيد مع Plus"),
 ("霓虹","Neon","نيون"),
 ("极光","Aurora","الشفق"),
 ("暖阳","Sunset","الغروب"),
 ("App 图标","App icon","أيقونة التطبيق"),
 ("换一枚桌面图标 · 默认免费，其余属 Plus","Pick a home-screen icon · default is free, others with Plus","اختر أيقونة الشاشة الرئيسية · الافتراضية مجانية والبقية مع Plus"),
 ("霓虹紫","Neon purple","بنفسجي نيون"),
 ("暗金","Dark gold","ذهبي داكن"),
 ("粉霓","Neon pink","وردي نيون"),
 ("地图皮肤 & App 图标","Map skins & app icons","سمات الخريطة وأيقونات التطبيق"),
 ("极光/暖阳地图配色，专属桌面图标","Aurora & sunset map palettes, exclusive icons","ألوان الشفق والغروب للخريطة وأيقونات حصرية"),
 # —— 统一主题 / Plus 门控扩展 ——
 ("主题色","Theme","السمة"),
 ("高亮色、地图与 App 图标一起换 · 霓虹免费，其余属 Plus","Accent colors, map and app icon switch together · Neon is free, others with Plus","تتبدل ألوان التمييز والخريطة وأيقونة التطبيق معًا · نيون مجاني والبقية مع Plus"),
 ("PLUS","PLUS","PLUS"),
 ("主题色 · 专属图标 · 小组件","Themes · exclusive icons · widgets","السمات · أيقونات حصرية · الودجات"),
 ("极光/暖阳整套主题（高亮+地图+图标），主屏小组件","Aurora & sunset full themes (accents + map + icon), Home Screen widgets","سمات الشفق والغروب الكاملة، وودجات الشاشة الرئيسية"),
 # —— 图鉴详情 / 邮票使用规则 ——
 ("点亮该国家即解锁 · 仅限该国足迹的明信片","Unlock by lighting the country · usable only on that country's footprints","افتحه بإضاءة الدولة · يُستخدم فقط على بصمات تلك الدولة"),
 ("节日前后 5 天限时可用（地区性节日仅限该地区足迹）· 收到贴此章的明信片即收集","Usable within 5 days around the festival (regional festivals limited to that region) · collect by receiving a card bearing it","يُستخدم خلال 5 أيام حول العيد (الأعياد الإقليمية لمنطقتها فقط) · اجمعه باستلام بطاقة تحمله"),
 ("已收集","Collected","تم جمعه"),
 ("未收集","Not collected","لم يُجمع"),
 ("使用限制","Usage","الاستخدام"),
 ("用法","How to use","طريقة الاستخدام"),
 ("可用窗口","Window","الفترة"),
 ("适用地区","Region","المنطقة"),
 ("收集方式","How to collect","طريقة الجمع"),
 ("说明","About","حول"),
 ("仅限该国足迹的明信片","Only on postcards from that country's footprints","فقط على بطاقات بصمات تلك الدولة"),
 ("寄明信片时在邮票选择器中选用","Pick it in the stamp selector when sending a postcard","اختره من منتقي الطوابع عند إرسال بطاقة"),
 ("节日前后 5 天，寄该地区足迹的明信片可选用","Within 5 days around the festival, on that region's footprints","خلال 5 أيام حول العيد، على بصمات تلك المنطقة"),
 ("收到贴此章的明信片即可收集","Receive a postcard bearing this seal to collect it","استلم بطاقة تحمل هذا الختم لجمعه"),
 ("任意明信片可选","Usable on any postcard","يُستخدم على أي بطاقة"),
 ("邮局盖章：明信片寄达后由 Lumi 邮局盖上，仅收件人翻面可见","Post office mark: stamped by the Lumi post office on delivery, visible only to the recipient","ختم البريد: يختمه بريد Lumi عند التسليم ويظهر للمستلم فقط"),
 # —— 典藏邮票（Plus）——
 ("典藏邮票 · PLUS","Premium stamps · PLUS","طوابع مميزة · PLUS"),
 ("终身会员专属 · 点亮该国家后，寄该地足迹的明信片可选用","Lifetime members only · light the country, then use on that place's postcards","حصري للأعضاء مدى الحياة · أضئ الدولة ثم استخدمه على بطاقات ذلك المكان"),
 ("终身会员解锁","Unlock with lifetime","يُفتح بالعضوية مدى الحياة"),
 ("成为终身会员，并点亮该国家","Become a lifetime member and light up the country","كن عضوًا مدى الحياة وأضئ الدولة"),
 ("仅限该城市足迹的明信片","Only on that city's footprints","فقط على بصمات تلك المدينة"),
 ("典藏国家邮票","Premium country stamps","طوابع الدول المميزة"),
 ("中国/美国/日本/阿联酋 14 枚典藏票，寄该地明信片专属可用","14 premium stamps for China/USA/Japan/UAE, exclusive to that place's postcards","14 طابعًا مميزًا للصين وأمريكا واليابان والإمارات، حصرية لبطاقات المكان"),
 # —— 典藏票名 ——
 ("上海天际线","Shanghai Skyline","أفق شنغهاي"),
 ("龙跃长城","Dragon over the Wall","التنين فوق السور"),
 ("长城·兵马俑","Great Wall & Warriors","السور العظيم والمحاربون"),
 ("摩天都市","Modern Cities","مدن حديثة"),
 ("永恒天际线","Eternal Skylines","آفاق خالدة"),
 ("西部风情","Western Heritage","تراث الغرب"),
 ("富士花信","Fuji Blossom","فوجي والأزهار"),
 ("浮世佳人","Ukiyo-e Beauty","جميلة أوكييو-إه"),
 ("富士浪涛","Fuji & Wave","فوجي والموجة"),
 ("江户渔人","Edo Fisherman","صياد إيدو"),
 ("金弧之城","City of Arcs","مدينة الأقواس"),
 ("大清真寺","Grand Mosque","المسجد الكبير"),
 ("艺术之岛","Isle of Art","جزيرة الفن"),
 ("哈利法塔","Burj Khalifa","برج خليفة"),
 ("阿布扎比","Abu Dhabi","أبوظبي"),
 ("迪拜","Dubai","دبي"),
 # —— 图鉴分类理顺：基础邮票 / 邮戳独立区 ——
 ("基础邮票","Basic stamps","الطوابع الأساسية"),
 ("普通邮票 · 默认解锁，任意明信片可选","Ordinary stamps · unlocked by default, usable on any postcard","طوابع عادية · مفتوحة افتراضيًا وتصلح لأي بطاقة"),
 ("邮戳 Postmarks","Postmarks","أختام البريد"),
 ("寄达后由 Lumi 邮局盖上，仅收件人可见 · 更多国家/地区/节日邮戳将陆续为会员推出","Stamped by the Lumi post office on delivery, visible only to the recipient · more country / region / festival postmarks coming for members","يختمه بريد Lumi عند التسليم ويظهر للمستلم فقط · المزيد من أختام الدول والمناطق والأعياد قادمة للأعضاء"),
 ("后续","Coming next","قادم"),
 ("更多按国家/地区/节日区分的邮戳将为终身会员推出","More postmarks by country / region / festival are coming for lifetime members","المزيد من الأختام حسب الدولة والمنطقة والعيد قادمة للأعضاء مدى الحياة"),
 ("敬请期待","Coming soon","قريبًا"),
 # —— v1.1 Lumi 邮局 ——
 ("站内直投未启用","In-app delivery isn't enabled","التسليم داخل التطبيق غير مفعّل"),
 ("邮局暂时不可用（%lld）","Post office unavailable (%lld)","مكتب البريد غير متاح (%lld)"),
 ("没有找到这个 Lumi 邮箱号","Lumi mailbox not found","لم يُعثر على صندوق Lumi هذا"),
 ("邮箱还没开通","Mailbox not set up yet","لم يُفتح الصندوق بعد"),
 ("订阅会自动续订，可随时在「设置 › Apple ID › 订阅」取消。付款将在确认购买时记入你的 Apple ID。","Subscriptions auto-renew; cancel anytime in Settings › Apple ID › Subscriptions. Payment is charged to your Apple ID at confirmation.","تتجدد الاشتراكات تلقائيًا؛ ألغِها من الإعدادات › Apple ID › الاشتراكات. يُخصم المبلغ من Apple ID عند التأكيد."),
 ("隐私政策","Privacy Policy","سياسة الخصوصية"),
 ("使用条款","Terms of Use","شروط الاستخدام"),
 ("已解锁 Lumi Plus ✦","Lumi Plus unlocked ✦","تم فتح Lumi Plus ✦"),
 ("感谢支持——所有 Plus 权益已为你打开。","Thanks for the support — all Plus perks are now on.","شكرًا لدعمك — كل مزايا Plus مفعّلة الآن."),
 ("好","OK","حسنًا"),
 ("邮寄明信片","Mail postcard","أرسل البطاقة"),
 ("明信片带 Lumi 水印","Postcard has a Lumi watermark","البطاقة تحمل علامة Lumi المائية"),
 ("升级 Plus 去水印 · 高清导出","Go Plus: no watermark · HD export","Plus: بلا علامة مائية · تصدير عالي الدقة"),
 ("升级","Upgrade","ترقية"),
 ("Lumi Plus 已解锁","Lumi Plus unlocked","Lumi Plus مفعّل"),
 ("升级 Lumi Plus","Upgrade to Lumi Plus","الترقية إلى Lumi Plus"),
 ("感谢支持——全部权益已开启 ✦","Thanks for the support — all perks on ✦","شكرًا لدعمك — كل المزايا مفعّلة ✦"),
 ("明信片去水印高清导出，更多增益陆续解锁","HD watermark-free postcards, with more perks to come","بطاقات عالية الدقة بلا علامة مائية، ومزايا أكثر قادمة"),
 # —— 护照本（复刻设计稿）——
 ("我的旅行护照","My travel passport","جواز سفري"),
 ("拟真","Classic","كلاسيكي"),
 ("星夜","Starlit","نجمي"),
 ("封面","Cover","الغلاف"),
 ("资料页","Bio Data","البيانات"),
 ("入境章","Entry Stamps","أختام الدخول"),
 ("入境章详情","Stamp Detail","تفاصيل الختم"),
 ("姓名","Name","الاسم"),
 ("签发","Authority","الجهة"),
 ("个国家已点亮","countries lit","دولة مضاءة"),
 ("入境口岸","Port","منفذ الدخول"),
 ("入境日期","Date","تاريخ الدخول"),
 ("入境方式","Means","وسيلة الدخول"),
 ("空运入境","By Air","جواً"),
 ("陆运入境","By Land","براً"),
 ("海运入境","By Sea","بحراً"),
  ("交通方式","Transportation methods","طريقة النقل"),
 # —— 新增徽章名 ——
 ("五十城","Fifty Cities","خمسون مدينة"),
 ("赤道穿越者","Equator Crosser","عابر خط الاستواء"),
 ("对跖之旅","Antipodes","النقاط المتقابلة"),
 ("四象限大师","Quadrant Master","سيّد الأرباع"),
 ("环球一周","Once Around","حول العالم"),
 ("四季旅人","Four Seasons","الفصول الأربعة"),
 ("家庭旅行","Family Caravan","قافلة العائلة"),
 ("独行灵魂","Solo Soul","روح منفردة"),
 ("奔向月球","To the Moon","إلى القمر"),
 # —— 新增徽章描述 ——
 ("全球累计打卡 50 座不同城市。","Check in at 50 distinct cities worldwide.","سجّل وصولًا في 50 مدينة مختلفة حول العالم."),
 ("在赤道附近（纬度 1° 内）点亮足迹。","Light a footprint within 1° of the equator.","أضئ بصمة ضمن 1° من خط الاستواء."),
 ("点亮两个近乎对跖的地点（地球两端）。","Light two near-antipodal points (opposite sides of Earth).","أضئ نقطتين متقابلتين تقريبًا على الأرض."),
 ("足迹覆盖南北 × 东西四个半球象限。","Cover all four hemispheres (N/S × E/W).","غطِّ الأنصاف الأربعة (شمال/جنوب × شرق/غرب)."),
 ("点亮地点的经度跨度超过 300°。","Span over 300° of longitude across your footprints.","امتد عبر أكثر من 300° من خطوط الطول."),
 ("在春夏秋冬四个季节都有足迹。","Have footprints in all four seasons.","سجّل بصمات في الفصول الأربعة."),
 ("和同行人一起点亮足迹。","Light a footprint together with companions.","أضئ بصمة برفقة مرافقين."),
 ("独自完成 5 次以上的足迹点亮。","Light 5+ footprints traveling solo.","أضئ 5 بصمات أو أكثر بمفردك."),
 ("旅行累计里程超过地月距离（384,400 公里）。","Travel a cumulative distance past the Moon (384,400 km).","اقطع مسافة تراكمية تتجاوز بُعد القمر (384,400 كم)."),
 # —— 徽章墙：只放点亮 + 更多二级页 ——
 ("查看更多徽章","See more badges","المزيد من الأوسمة"),
 ("更多徽章","More badges","المزيد من الأوسمة"),
 ("%lld 进行中 · %lld 未解锁","%1$lld in progress · %2$lld locked","%1$lld قيد التقدم · %2$lld مقفل"),
 ("还没点亮徽章 · 去点亮第一个地方","No badges yet · light your first place","لا أوسمة بعد · أضئ أول مكان"),
 ("全部徽章已点亮 ✦","All badges unlocked ✦","فُتحت كل الأوسمة ✦"),
 # —— 明信片：From / 发送日期 / QR / 墙排序 ——
 ("寄自 %@","From %@","من %@"),
 ("发送日期","Send date","تاريخ الإرسال"),
 ("寄自","From","من"),
 ("你的名字","Your name","اسمك"),
 ("同时导入照片","Also import photos","استيراد الصور أيضًا"),
 ("把识别到的照片一并加入足迹，丰富时间线","Add matched photos to footprints to enrich your timeline","أضف الصور المطابقة إلى البصمات لإثراء الخط الزمني"),
 ("扫码用 Lumi 收下这张明信片","Scan with Lumi to receive this postcard","امسح بـ Lumi لاستلام هذه البطاقة"),
 ("按接收时间","By received","حسب الاستلام"),
 ("按来源地 A–Z","By place A–Z","حسب المكان A–Z"),
 # —— 订阅账单状态 ——
 ("自动续订已开启","Auto-renew on","التجديد التلقائي مُفعّل"),
 ("自动续订已关闭","Auto-renew off","التجديد التلقائي مُعطّل"),
 ("下次续订","Renews","يتجدد"),
 ("到期","Expires","ينتهي"),
 ("还没有个人信息","No personal info yet","لا توجد معلومات شخصية"),
 ("设置姓名和国籍，生成你的专属护照本","Set your name and nationality to generate your passport","عيّن اسمك وجنسيتك لإنشاء جواز سفرك"),
 ("添加个人信息","Add personal info","أضف معلومات شخصية"),
 ("旅行者","Traveler","مسافر"),
 ("护照风格","Passport Style","نمط الجواز"),
 # —— 明信片样式 / 邮票（复刻设计稿）——
 ("样式","Style","النمط"),
 ("邮票","Stamp","الطابع"),
 ("翻面","Flip","اقلب"),
 ("寄给","To","إلى"),
 ("远方的你","Someone far away","شخص بعيد"),
 ("复古","Vintage","كلاسيكي"),
 ("现代","Modern","حديث"),
 ("插画","Vivid","رسوم"),
 ("航空","Air","جوي"),
 ("城市","City","مدينة"),
 # —— 语言切换 / 编辑重新定位 ——
 ("语言已切换","Language changed","تم تغيير اللغة"),
 ("请关闭并重新打开 Lumi 以应用新语言。","Please quit and reopen Lumi to apply the new language.","يرجى إغلاق Lumi وإعادة فتحه لتطبيق اللغة الجديدة."),
 ("切换后需重启 App 生效。也可在「系统设置 › Lumi › 语言」中调整。","Restart the app to apply. You can also change it in Settings › Lumi › Language.","أعد تشغيل التطبيق للتطبيق. يمكنك أيضًا تغييرها من الإعدادات › Lumi › اللغة."),
 ("搜索真实地点，重新定位","Search a real place to relocate","ابحث عن مكان حقيقي لإعادة التحديد"),
 ("已定位：%@","Located: %@","تم التحديد: %@"),
 ("往来的人","People you've exchanged with","من تبادلت معهم"),
 ("空运","Air","شحن جوي"),
 ("陆运","Land","شحن بري"),
 ("海运","Sea","شحن بحري"),
 ("推荐","Spots","أماكن"),
 ("最佳季节","Best season","أفضل موسم"),
 ("中文显示中文、阿拉伯语显示阿语，其余默认英文；如需单独指定，可在「系统设置 › Lumi」里调整。","Chinese shows Chinese, Arabic shows Arabic, everything else defaults to English. To override, use Settings › Lumi.","الصينية بالصينية، والعربية بالعربية، وما عداهما الإنجليزية افتراضيًا. للتخصيص استخدم الإعدادات › Lumi."),
 # —— 设置页小组件预览卡 mock 文案 ——
 ("点亮战绩","Lit Stats","الإحصاءات"),
 ("个国家 · 全球 5%","countries · 5% of world","دولة · 5% من العالم"),
 ("已点亮 12 国","12 countries lit","12 دولة مضاءة"),
 ("去年此刻你在 东京 ✦","A year ago: Tokyo ✦","قبل عام: طوكيو ✦"),
 # —— 星迹「最新」标记 ——
 ("最新","Latest","الأحدث"),
 # —— 设置页：反馈与建议 ——
 ("反馈与建议","Feedback","ملاحظات"),
 ("有想法或遇到问题？写信告诉我们","Got ideas or issues? Drop us a line","لديك أفكار أو مشكلات؟ راسلنا"),
 ("发送反馈邮件","Send feedback email","أرسل بريد الملاحظات"),
 ("点这里发邮件给我们","Tap to email us","انقر لمراسلتنا"),
 ("Lumi 反馈","Lumi Feedback","ملاحظات Lumi"),
 # —— 相册导入进度 / 预计剩余时间 ——
 ("已识别 %lld / %lld 处","%1$lld / %2$lld places found","%1$lld / %2$lld مكان"),
 ("预计还需约 %lld 秒","About %lld s left","يتبقى نحو %lld ث"),
 ("预计还需约 %lld 分钟","About %lld min left","يتبقى نحو %lld د"),
 ("即将完成…","Almost done…","على وشك الانتهاء…"),
 # —— 多徽章同时解锁汇总 ——
 ("点亮了 %lld 个徽章","Unlocked %lld badges","فتحت %lld أوسمة"),
 # —— 成就页统计汇总 ——
 ("徽章墙","Badge Wall","جدار الأوسمة"),
 ("已访问 UN 成员国","UN member states visited","دول أعضاء بالأمم المتحدة"),
 # —— 成就数据报告分享 ——
 ("UN 成员国","UN members","أعضاء الأمم المتحدة"),
 ("分享成就报告","Share stats report","مشاركة تقرير الإحصاءات"),
 ("点亮你的旅行足迹 · Lumi","Light up your journey · Lumi","أضئ رحلتك · Lumi"),
 # —— 全屏地图：国家去过的城市记录 ——
 ("看看在这里去过的城市","See cities you've visited here","شاهد المدن التي زرتها هنا"),
 ("未指定城市","City not set","مدينة غير محددة"),
 ("还没去过","Not visited yet","لم تُزر بعد"),
 # —— 全屏地图：颜色图例（去过 / 心愿）——
 ("去过","Visited","زرتها"),
 ("心愿","Wishlist","الأمنيات"),
 # —— 全屏地图：国家操作半浮窗（hub）——
 ("已点亮 · %lld 城","Lit · %lld cities","مضاءة · %lld مدينة"),
 ("还没点亮","Not lit yet","لم تُضأ بعد"),
 ("再记一次","Log again","سجّل مجددًا"),
 ("我去过这里","I've been here","لقد زرت هنا"),
 ("已在心愿","Wishlisted","في الأمنيات"),
 ("加入心愿","Add wish","أضف أمنية"),
 ("%lld 城 · 共 %lld 次记录","%1$lld cities · %2$lld records","%1$lld مدينة · %2$lld سجل"),
 ("推荐城市","Suggested cities","مدن مقترحة"),
 ("点亮","Light up","أضئ"),
 ("已点亮","Lit","مضاءة"),
 # —— 新版本检测 / 更新提示（A）——
 ("发现新版本 %@","New version %@ available","يتوفر إصدار جديد %@"),
 ("更新后可获得更多徽章 / 样式等新内容","Update for more badges, styles, and new content","حدّث للحصول على أوسمة وأنماط ومحتوى جديد"),
 ("去更新","Update","تحديث"),
 ("稍后","Later","لاحقًا"),
 ("跳过此版本","Skip this version","تخطّ هذا الإصدار"),
 # —— 设置页：关于 / 版本（C）——
 ("关于","About","حول"),
 ("当前版本 %@","Version %@","الإصدار %@"),
 ("有新版本可更新","Update available","يتوفر تحديث"),
 ("已是最新版本","You're up to date","أنت على آخر إصدار"),
 ("查看本次更新","See what's new","ما الجديد"),
 # —— 本次更新 What's New（B）——
 ("本次更新 ✦","What's New ✦","ما الجديد ✦"),
 ("知道了","Got it","حسنًا"),
 ("心愿单上地图","Wishlist on the map","قائمة الأمنيات على الخريطة"),
 ("全屏地图用霓虹青标出想去的地方，和去过的粉色一眼区分","The full-screen map marks wishlist spots in neon cyan, distinct from visited pink","تُبرز الخريطة أماكن الأمنيات بالسماوي النيوني، تمييزًا عن الوردي المُزار"),
 ("点国家更顺手","Tapping a country, refined","نقر الدولة، أسهل"),
 ("点一个国家，弹出一个面板：点亮 / 心愿 / 看去过的城市 / 推荐城市一键操作","Tap a country for one panel: light up, wishlist, visited cities, and one-tap suggested cities","انقر دولة للوحة واحدة: إضاءة، أمنية، المدن المزارة، ومدن مقترحة بنقرة"),
 ("成就报告可分享","Shareable stats report","تقرير إنجازات قابل للمشاركة"),
 ("把你的世界点亮战绩导成一张紫色霓虹海报，发出去","Export your world progress as a purple-neon poster to share","صدّر تقدمك حول العالم كملصق نيوني بنفسجي للمشاركة"),
 ("用 Apple 登录","Sign in with Apple","تسجيل الدخول عبر Apple"),
 ("在设置里用 Apple 一键登录，为后续会员权益打底","Sign in with Apple in Settings, paving the way for member perks","سجّل عبر Apple من الإعدادات، تمهيدًا لمزايا العضوية"),
 ("更跟手的反馈","More tactile feedback","استجابة لمسية أفضل"),
 ("点亮、切换、解锁徽章都加了触觉反馈","Haptics added to lighting, switching, and badge unlocks","لمسات اهتزازية عند الإضاءة والتبديل وفتح الأوسمة"),
 # —— 分享到 Instagram ——
 ("分享到 Instagram","Share to Instagram","شارك على إنستغرام"),
 # —— 个性化展示台（Customize showcase）——
 ("个性化","Customize","تخصيص"),
 ("小组件 & 样式","Widgets & styles","الودجات والأنماط"),
 ("浏览小组件、明信片样式、邮票与护照风格，点一下即应用","Browse widgets, postcard styles, stamps and passport looks — tap to apply","تصفّح الودجات وأنماط البطاقات والطوابع وأشكال الجواز — انقر للتطبيق"),
 ("把旅行进度放上主屏 / 锁屏","Put your travel progress on the Home / Lock Screen","ضع تقدّم رحلتك على الشاشة الرئيسية / المقفلة"),
 ("主屏显示已点亮国家数与全球占比","Lit countries and world percent on your Home Screen","الدول المضاءة ونسبة العالم على شاشتك الرئيسية"),
 ("去过国家的国旗集合，一眼看遍","All the flags of countries you've visited, at a glance","كل أعلام الدول التي زرتها، بلمحة"),
 ("回看往年此刻你在的地方","Revisit where you were on this day in past years","تذكّر أين كنت في مثل هذا اليوم سابقًا"),
 ("明信片样式","Postcard styles","أنماط البطاقات"),
 ("选一个默认卡面，分享时即用","Pick a default card face, used when you share","اختر واجهة افتراضية تُستخدم عند المشاركة"),
 ("默认邮票贴图","Default stamp","الطابع الافتراضي"),
 ("护照本封面与内页风格","Passport cover and page style","نمط غلاف وصفحات الجواز"),
 # —— 添加小组件到桌面 指引 ——
 ("添加到桌面","Add to Home Screen","أضف إلى الشاشة الرئيسية"),
 ("长按主屏空白处，进入编辑状态","Touch and hold an empty area of the Home Screen","المس مطوّلًا منطقة فارغة بالشاشة الرئيسية"),
 ("点左上角的「+」号","Tap the “+” in the top-left corner","انقر «+» في الزاوية العلوية اليسرى"),
 ("搜索「Lumi」","Search for “Lumi”","ابحث عن «Lumi»"),
 ("选择小组件与尺寸（小 / 中），点「添加小组件」","Pick a widget and size (small / medium), then Add Widget","اختر ودجت وحجمًا (صغير / متوسط) ثم أضف الودجت"),
 ("小组件会跟随系统语言显示","Widgets follow your system language","تتبع الودجات لغة نظامك"),
 ("东京","Tokyo","طوكيو"),
 # —— 账户 / Sign in with Apple ——
 ("账户","Account","الحساب"),
 ("已登录","Signed in","تم تسجيل الدخول"),
 ("通过 Apple 登录","Signed in with Apple","تسجيل الدخول عبر Apple"),
 ("退出登录","Sign out","تسجيل الخروج"),
 ("登录以同步与解锁会员权益（后续）","Sign in to sync and unlock member perks (soon)","سجّل الدخول للمزامنة وفتح مزايا العضوية (قريبًا)"),
 ("直寄","Send direct","إرسال مباشر"),
 ("直寄到 Lumi 邮箱","Send to a Lumi mailbox","أرسل إلى صندوق بريد Lumi"),
 ("我的 Lumi 邮箱号","My Lumi mailbox","صندوق بريدي في Lumi"),
 ("开通我的邮箱","Open my mailbox","افتح صندوق بريدي"),
 ("复制邮箱号","Copy mailbox No.","نسخ رقم الصندوق"),
 ("输入对方的 Lumi 邮箱号，明信片直接寄进 Ta 的 App","Enter their Lumi mailbox number and the postcard lands right in their app","أدخل رقم صندوق بريد Lumi الخاص بهم وستصل البطاقة مباشرة إلى تطبيقهم"),
 ("从往来的人里选","Pick from your circle","اختر من معارفك"),
 ("已寄出 · 等待送达","Sent · awaiting delivery","أُرسلت · بانتظار التسليم"),
 ("已送达 ✓","Delivered ✓","تم التسليم ✓"),
 ("寄出成功！对方打开 Lumi 就能收到","Sent! They'll get it when they open Lumi","أُرسلت! ستصلهم عند فتح Lumi"),
 ("把邮箱号告诉朋友，Ta 就能把明信片直接寄进你的 App","Share your mailbox number and friends can send postcards straight into your app","شارك رقم صندوقك ليتمكن أصدقاؤك من إرسال البطاقات مباشرة إلى تطبيقك"),
 ("LUMI-XXXXXX","LUMI-XXXXXX","LUMI-XXXXXX"),
 ("Lumi 邮箱号（选填，填了可直寄）","Lumi mailbox No. (optional — fill in to send direct)","رقم صندوق Lumi (اختياري — املأه للإرسال المباشر)"),
 ("已寄达对方邮箱","Delivered to their mailbox","وصلت إلى صندوقهم"),
 ("分享图片","Share image","مشاركة الصورة"),
 ("对方也用 Lumi？在上方填 Ta 的邮箱号即可直寄","They use Lumi too? Enter their mailbox number above to send direct","هل يستخدمون Lumi أيضًا؟ أدخل رقم صندوقهم أعلاه للإرسال المباشر"),
 ("价格没加载出来（网络不佳或 App Store 暂时无响应）","Prices didn't load (weak network or the App Store isn't responding)","لم تُحمَّل الأسعار (شبكة ضعيفة أو App Store لا يستجيب)"),
 ("重新加载","Reload","إعادة التحميل"),
 ("寄给 Ta","Sent to them","أرسلت لهم"),
 ("收到 Ta 的","Received from them","وصلتك منهم"),
 ("寄明信片时从「往来的人」点选 Ta，即可直寄","Pick them from your circle when sending a postcard to send direct","اخترهم من معارفك عند إرسال بطاقة للإرسال المباشر"),
 ("搜索国家 / 地区","Search countries & regions","ابحث عن الدول والمناطق"),
 ("点亮世界地图 · 寄一张会盖邮戳的明信片","Light up the world map · send a postmarked postcard","أضئ خريطة العالم · أرسل بطاقة بختم البريد"),
 ("扫码了解 Lumi","Scan to meet Lumi","امسح لتتعرف على Lumi"),
 ("登录失败","Sign-in failed","فشل تسجيل الدخول"),
 ("中国","China","الصين"),
 ("按国家 A–Z","By country A–Z","حسب الدولة أ–ي"),
 ("寄卡人","From","المرسل"),
 ("回寄明信片","Send one back","أرسل بطاقة بالمقابل"),
 ("选一个足迹回寄","Pick a footprint to send back","اختر أثرًا للرد"),
 ("还没有可回寄的足迹，先去点亮一个地方吧","No footprints to send yet — light up a place first","لا آثار للإرسال بعد — أضئ مكانًا أولًا"),
 ("一起点亮世界地图、在 Lumi 互寄明信片吧 ✦","Let's light up the world map and swap postcards on Lumi ✦","لنضئ خريطة العالم ونتبادل البطاقات على Lumi ✦"),
 ("把 Lumi 介绍给朋友","Tell a friend about Lumi","أخبر صديقًا عن Lumi"),
 ("推荐给朋友","Tell a friend","أخبر صديقًا"),
 ("把 Lumi 分享给会喜欢它的人","Share Lumi with someone who'd love it","شارك Lumi مع من سيحبه"),
 ("商店","Store","المتجر"),
 ("邮票包 · 邮戳包 · 更多装扮","Stamp packs · postmarks · more","حزم الطوابع والأختام والمزيد"),
 ("邮票、邮戳与更多装扮，把每一张明信片寄得更好看","Stamps, postmarks and more — make every postcard prettier","طوابع وأختام والمزيد — اجعل كل بطاقة أجمل"),
 ("邮票包","Stamp packs","حزم الطوابع"),
 ("邮戳包","Postmark packs","حزم الأختام"),
 ("已拥有","Owned","مملوك"),
 ("免费","Free","مجاني"),
 ("即将上架","Coming soon","قريبًا"),
 ("共 %lld 枚","%lld pieces","%lld قطعة"),
 ("明信片正面素材：城市插画 · 画框 · 复古滤镜","Card fronts: city art · frames · vintage filters","واجهات البطاقات: رسوم المدن · إطارات · فلاتر قديمة"),
 ("地区票仅限对应国家足迹的明信片使用","Regional stamps only work on postcards from that country","طوابع المناطق تعمل فقط على بطاقات ذلك البلد"),
 ("已拥有 · 寄明信片时可选用","Owned · available when sending postcards","مملوك · متاح عند إرسال البطاقات"),
 ("升级终身会员，免费领取","Go lifetime Plus and claim it free","اشترك مدى الحياة واحصل عليه مجانًا"),
 ("购买 %@","Buy %@","اشترِ %@"),
 ("会员专享折扣价","Member discount applied","خصم الأعضاء مُطبق"),
 ("该资源包暂未上架，敬请期待","This pack isn't on sale yet — stay tuned","هذه الحزمة غير متاحة بعد — ترقبوا"),
 ("云同步未启用","Cloud sync not enabled","المزامنة السحابية غير مفعلة"),
 ("请先登录","Please sign in first","يرجى تسجيل الدخول أولًا"),
 ("云同步暂时不可用（%lld）","Cloud sync unavailable (%lld)","المزامنة غير متاحة (%lld)"),
 ("云同步已开启","Cloud sync on","المزامنة السحابية مفعلة"),
 ("云同步未连接","Cloud sync not connected","المزامنة غير متصلة"),
 ("上次同步 %@","Last synced %@","آخر مزامنة %@"),
 ("立即同步","Sync now","زامن الآن"),
 ("资源包 · 商店","Store packs","حزم المتجر"),
 ("来自商店的扩充邮票包 · 拥有后寄对应足迹的明信片可选用","Expansion packs from the store · use on matching footprints once owned","حزم إضافية من المتجر · تُستخدم على الآثار المطابقة بعد امتلاكها"),
 ("云同步 · 终身会员专属","Cloud sync · lifetime members only","المزامنة السحابية · للأعضاء الدائمين فقط"),
 ("升级后足迹与心愿自动云端备份，换机即恢复","Upgrade to auto-back up footprints & wishes — restore on any device","بعد الترقية تُنسخ آثارك وأمنياتك تلقائيًا وتُستعاد على أي جهاز"),
 ("云端同步与换机恢复","Cloud sync & device transfer","المزامنة السحابية ونقل الأجهزة"),
 ("足迹与心愿自动备份云端，换机登录即恢复","Footprints & wishes back up automatically — sign in on a new device to restore","تُنسخ الآثار والأمنيات تلقائيًا — سجّل الدخول على جهاز جديد للاستعادة"),
 ("明信片太大寄不动了——换一张小一点的照片试试","This postcard is too heavy to send — try a smaller photo","البطاقة أثقل من أن تُرسل — جرّب صورة أصغر"),
]

# Resolve duplicate "国家" (Country vs Countries): keep two distinct? They share key -> can't.
# Profile uses "国家"(Countries) and detail statCard uses "国家"(Country). Same Chinese key -> one translation.
# Use "Countries" (plural) as it reads fine in both; drop the duplicate entry.
seen = {}
for zh, en, ar in S:
    if zh in seen:
        # keep first; skip dup silently (e.g. 国家, 城市 appear twice with same zh)
        continue
    seen[zh] = (en, ar)

strings = {}
for zh, (en, ar) in seen.items():
    strings[zh] = {"localizations": {
        # 显式写入源语言 zh-Hans（值=中文 key）。否则 developmentRegion=en 时，
        # 中文系统找不到 zh-Hans 资源会回退到英文（= 之前“中文系统全英文”的根因）。
        "zh-Hans": {"stringUnit": {"state": "translated", "value": zh}},
        "en": {"stringUnit": {"state": "translated", "value": en}},
        "ar": {"stringUnit": {"state": "translated", "value": ar}},
    }}

catalog = {"sourceLanguage": "zh-Hans", "strings": strings, "version": "1.0"}
out = sys.argv[1]
with open(out, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
    f.write("\n")
print(f"wrote {len(strings)} keys -> {out}")
